### ISSUE TITLE
package.json mail file location incorrect

### ISSUE THREAD

**Issue by paulstefanday** [RemiAWE/ng-flat-datepicker#6]
Hey, I couldn't import this as a module becasue the package.json "main" attribute says "index.js" instead of "dist/ng-flat-datepicker.js"

**Comment by RemiAWE** [comment]
Hi, yes it's an error, i'm sorry and I will correct that today. In which case do you need this ?

**Comment by RemiAWE** [comment]
Closed in 16c40ab0ff0007c81338e9fd7d3b0630b0eb5160
