### ISSUE TITLE
minDate and maxDate config does not work as expected

### ISSUE THREAD

**Issue by tomexx** [RemiAWE/ng-flat-datepicker#7]
minDate and maxDate config values does not disable click events in the datepicker. They only add classes isDisabled to visualise the allowed timerange, however user is still able to select a date which is not in the allowed range.

**Comment by diegochavez** [comment]
Hi @tomexx i've added the solutions to this problem, could you test and let us know if this work for you, i just summited a pull request.

Best,

 https://github.com/diegochavez/ng-flat-datepicker/commit/5daaee91b7e7e95b192c7f97fc990ff03e3f9563

**Comment by RemiAWE** [comment]
Thank you @diegochavez ! I have implemented your fix.

**Comment by diegochavez** [comment]
That's great mate 👍
